on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

name: phpunit

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['7.4', '8.0', '8.1', '8.2']
      stability: >-
        ['prefer-stable']
