on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

name: static analysis

jobs:
  psalm:
    uses: spiral/gh-actions/.github/workflows/psalm.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
